travis:
  secure:
    BINSTAR_TOKEN: einAr5qlJ/8wSwtVeUlF2DZQutX+Ft9RDYliDFJrdNNwtxYAU1BawBjuD+yTpxsn4YRuhT1yWSJFEDbUeia5MZ4fOrMfWm8Aylp4/aC5kOCLB/ztCTDVmex4QPwFY4d2YXxJ4hwy1+9Oc0yAEcIH9ezh+VDmesvt02FT67SXB3qVezR6pDN7Hbz5yY14g63D7+6jg7vz+c0v8ZcFaRrpmCCrg41FLKxyU0atQpjhxrGT97rtlKjEWcL1SS0dTwIm0QhIUrMpxn6lCybLZHIq3eoOpK39KNSSF3iaNPBN4Sj4ymD8Ek8E3S1mTtOU80N7XtQdtu7+rZbQ6psjeFeL+ZlqVMiGlfj6JwzAaxMD//CVi/yCmrggYM2Io5pOzA3YwtAdnoRULOcvCAFXiJZYAV7cUdL/hIaA2X8DkbmdV01Eqat9/Gg/Bws6Oix4geg2+/AiFxQbE6hOXk3LIgWTLHUNn0ZY44J+mVg1Br2oLAMxBW//I17CVQ1YVmAdQL0hPgxF0nM4b1WCRO+hmHXDN1FFij7m8bGx5+4yNTNAN2zyNZek1uzrt16r3OYSRN5ZRV40mqw5UHp4MNjo9LSJt5fGApUGVsQbn/c1sHmi1LY7Lvz5a4U7pOcPxn0JrOVxdLiiyq3Z9UFtabkFLv2RkBC8/dRsUrJAt/68i4SR0Hk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
